import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv('MONGO_URI')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME')
MONGO_TASK_1_COLLECTION = os.getenv('MONGO_TASK_1_COLLECTION')
MONGO_MAINTAINFEE_SERVICE_COLLECTION = os.getenv('MONGO_MAINTAINFEE_SERVICE_COLLECTION')
MONGO_MAINTAINFEE_RESOURCE_COLLECTION = os.getenv('MONGO_MAINTAINFEE_RESOURCE_COLLECTION')
MONGO_MAINTAINHOUR_RESOURCE_COLLECTION = os.getenv('MONGO_MAINTAINHOUR_RESOURCE_COLLECTION')
MONGO_MAINTAINHOUR_SERVICE_COLLECTION = os.getenv('MONGO_MAINTAINHOUR_SERVICE_COLLECTION')
MONGO_MAINTAIN_PLAN = os.getenv('MONGO_MAINTAIN_PLAN')
MONGO_MAINTAIN_SERVICE = os.getenv('MONGO_MAINTAIN_SERVICE')
REDIS_HOST = os.getenv('REDIS_HOST')